version: "3"
services:
  eurekaserver:
    image: javi13dev/proyecto_viajes:eurekaserver
    ports:
    - 8761:8761
    networks:
    - mi-red
  shotel:
    image: javi13dev/proyecto_viajes:serviciohotel
    ports:
    - 8000:8000
    environment:
    - DATABASE_URL=jdbc:mysql://mi-mysql:3306/viajes
    - IP_HOST=192.168.3.78
    - PORT_HOST=8000
    - USUARIO_BBDD=root
    - PASS_BBDD=root
    networks:
    - mi-red
    depends_on:
    - eurekaserver
  scliente:
    image: javi13dev/proyecto_viajes:serviciocliente
    ports:
    - 8500:8500
    environment:
    - DATABASE_URL=jdbc:mysql://mi-mysql:3306/viajes
    - IP_HOST=192.168.3.78
    - PORT_HOST=8500
    - USUARIO_BBDD=root
    - PASS_BBDD=root
    networks:
    - mi-red
    depends_on:
    - eurekaserver
  svuelo:
    image: javi13dev/proyecto_viajes:serviciovuelo
    ports:
    - 9000:9000
    environment:
    - DATABASE_URL=jdbc:mysql://mi-mysql:3306/viajes
    - DATABASE_URL_SECURITY=jdbc:mysql://mi-mysql:3306/springsecurity
    - IP_HOST=192.168.3.78
    - PORT_HOST=9000
    - USUARIO_BBDD=root
    - PASS_BBDD=root
    networks:
    - mi-red
    depends_on:
    - eurekaserver
  sreserva:
    image: javi13dev/proyecto_viajes:servicioreserva
    ports:
    - 9500:9500
    environment:
    - DATABASE_URL=jdbc:mysql://mi-mysql:3306/viajes
    - DATABASE_URL_SECURITY=jdbc:mysql://mi-mysql:3306/springsecurity
    - IP_HOST=192.168.3.78
    - PORT_HOST=9500
    - USUARIO_BBDD=root
    - PASS_BBDD=root
    - USUARIO=user1
    - CONTRA=user1
    networks:
    - mi-red
    depends_on:
    - eurekaserver
  gateway:
    image: javi13dev/proyecto_viajes:gateway
    ports:
    - 11000:11000
    environment:
    - URL_EUREKA=http://192.168.3.78:8761/eureka
    - PORT_HOST=11000
    depends_on:
    - scliente
    - shotel
    - svuelo
    - sreserva
    networks:
    - mi-red
networks:
  mi-red:
    external: true