# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: ${PORT_HOST}
  servlet:
    context-path: /hoteles
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${USUARIO_BBDD}
    password: ${PASS_BBDD}
  application:
    name: servicio-hoteles
eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}
  instance:
    hostname: ${IP_HOST}
    non-secure-port: ${PORT_HOST}