# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: 9500
  servlet:
    context-path: /reservas
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.3.32:3306/viajes
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: servicio-reservas
eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}
  instance:
    hostname: ${IP_HOST}
    non-secure-port: ${PORT_HOST}
usuario: ${USUARIO}
contra: ${CONTRA}
